### ISSUE TITLE
[Improvement]: configuration documentation

### ISSUE THREAD

**Issue by thijs1988** [pimcore/elasticsearch-client#8]
### Improvement description

It's not clear to me how to configure the pimcore elasticsearch client. In what file to i need to add the configuration?

pimcore_elasticsearch_client:
    es_clients:
        default:
            hosts: ['elastic:9200']
            username: 'elastic'
            password: 'somethingsecret'
            logger_channel: 'pimcore.elasicsearch'
        statistics:
            hosts: ['statistics-node:9200']
            logger_channel: 'pimcore.statistics'

**Comment by fashxp** [comment]
This is a standard symfony configuration - as stated in the readme.
So you need to place the configuration in any configuration file that is loaded by symfony. For more information find the [symfony docs](https://symfony.com/doc/current/configuration.html).

**Comment by moiashvin** [comment]
@fashxp - can you please help me with similar topic. 

1. I have ES running in a container and can access it using localhost:9200 (container name is "es-container", service name is elasticsearch in docker).

2. i have added module pimcore/elasticsearch-client via composer require command 

3. enabled the module in bundles.php
Pimcore\Bundle\ElasticsearchClientBundle\PimcoreElasticsearchClientBundle::class => ['all' => true],

4. added the following configuration in config.yaml
pimcore_elasticsearch_client:
    es_clients:
        default:
            hosts: ['elasticsearch:9200']
            logger_channel: 'pimcore.elasicsearch'
        statistics:
            hosts: ['statistics-node:9200']
            logger_channel: 'pimcore.statistics

advanced_object_search:
    es_client_name: default

advanced_object_search:
    # Prefix for index names
    index_name_prefix: 'advanced_object_search_'`

I excluded the username/password as i don't have it set in the ES instance


With all above, I still can't get the Advanced Object Search working.
If I run command php bin/console advanced-object-search:re-index
I have error "there are no commands deefined in the "advanced-object-search" namespace.

Am I missing anything here? Any guidance will be helpful.

Thanks,
Ashvin
